### ISSUE TITLE
Allow lenient parsing at the end of the log line

### ISSUE THREAD

**Issue by borinquenkid** [nielsbasjes/logparser#36] opened 2016-11-08 15:10 UTC
I was having issues parsing lines like this until I made the change on the patch (I masked the ips)

`*.*.*.* - - [31/Jul/2016:03:07:00 -0500] 4679405 4 "GET /admin/cc_info.php?done=1&mv_action=done&_r=106 HTTP/1.1" 200 2618 "https://*.*.*/admin/cc_info.php?done=1&mv_action=done&_r=106" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"`
I changed line 162 of TokenFormatDissector `regex.append("$.*");` 
[lenient_eol_parsing_patch.txt](https://github.com/nielsbasjes/logparser/files/578489/lenient_eol_parsing_patch.txt)

Could this be integrated

**Comment by nielsbasjes** [comment] 2016-11-08 15:46
Please specify the logformat and what goes wrong in the mentioned logline. I currently do not see how matching beyond the end of the line can make a difference?

**Comment by nielsbasjes** [comment] 2016-11-08 20:11
I had a good look at your log line and to me it seems like the 'combined' logformat with two extra numbers directly after the time field (I'm guessing something like %B and %D). 
I did a quick test with this logformat:

```
%h %l %u %t %B %D "%r" %>s %b "%{Referer}i" "%{User-Agent}i"
```

The result is the system parses this completely fine:

```
    public class Record extends HashMap<String, String> {
        @Override
        public String put(String key, String value) {
            return super.put(key, value);
        }
    }

    @Test
    public void testReportedProblem() throws Exception {
        String line = "1.1.1.1 - - [31/Jul/2016:03:07:00 -0500] 4679405 4 \"GET /admin/cc_info.php?done=1&mv_action=done&_r=106 HTTP/1.1\" 200 2618 \"https://example.com/admin/cc_info.php?done=1&mv_action=done&_r=106\" \"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36\"";
        String format = "%h %l %u %t %B %D \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"";

        String[] params = {
            "STRING:request.firstline.uri.query.done",
            "STRING:request.firstline.uri.query.mv_action",
            "STRING:request.firstline.uri.query._r",
        };

        Parser<Record> parser = new ApacheHttpdLoglineParser<>(Record.class, format);
        parser.addParseTarget(Record.class.getMethod("put", String.class, String.class), Arrays.asList(params));

        Map<String, String> values = parser.parse(new Record(), line);
        System.out.println(values);
    }

``` 

I'm closing this for now because I cannot reproduce it.

**Closed by nielsbasjes** 2016-11-08 20:11 UTC
